name: Build release unsigned apk
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: check
        uses: actions/checkout@v3

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - run: chmod 777 ./gradlew && ./gradlew build --no-daemon

      - name: Build inrt template
        run: |
          chmod 777 ./gradlew
          ./gradlew inrt:assembleTemplate
          ls

      - name: Build App
        run: |
          ls  inrt/build/outputs/apk/template/release
          mv  inrt/build/outputs/apk/template/release/*.apk  app/src/main/assets/template.apk
          ls  app/src/main/assets
          ./gradlew app:assembleCommonRelease

      - name: Upload apk to artifact 1
        uses: actions/upload-artifact@v3
        with:
          name: app-common-arm64-v8a-release-unsigned.apk
          path: app/build/outputs/apk/common/release/app-common-arm64-v8a-release-unsigned.apk

      - name: Upload apk to artifact 2
        uses: actions/upload-artifact@v3
        with:
          name: app-common-armeabi-v7a-release-unsigned.apk
          path: app/build/outputs/apk/common/release/app-common-armeabi-v7a-release-unsigned.apk

      - name: Upload apk to artifact 3
        uses: actions/upload-artifact@v3
        with:
          name: app-common-universal-release-unsigned.apk
          path: app/build/outputs/apk/common/release/app-common-universal-release-unsigned.apk